SET GLOBAL local_infile = true;

-- LOAD DATA LOCAL INFILE 'data/clean/questions.csv'
LOAD DATA LOCAL INFILE './questions.csv'
INTO TABLE questions
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- LOAD DATA LOCAL INFILE 'data/clean/answers.csv'
LOAD DATA LOCAL INFILE './answers.csv'
INTO TABLE answers
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED by '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- LOAD DATA LOCAL INFILE 'data/clean/answers_photos.csv' INTO TABLE photos
LOAD DATA LOCAL INFILE './answers_photos.csv' INTO TABLE photos
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED by '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;